---@class LuaClass
---@field Main Main
---@field TestUI TestUI
---@field CoreInit CoreInit
---@field Coroutine Coroutine
---@field CSharpBinding CSharpBinding
---@field Functions Functions
---@field LuaClass LuaClass
---@field LuaClassList LuaClassList
---@field LuaClassTips LuaClassTips
---@field Timer Timer
---@field Extension Extension
---@field ExtensionInit ExtensionInit
---@field FPEx FPEx
---@field GameObjectEx GameObjectEx
---@field GComponentEx GComponentEx
---@field StringEx StringEx
---@field TSVector2Ex TSVector2Ex
---@field Vector2Ex Vector2Ex
---@field Vector3Ex Vector3Ex
---@field UIManager UIManager
---@field UI_Package1_Component1 UI_Package1_Component1
---@field UI_Package1_lalala UI_Package1_lalala
---@field StringUtil StringUtil
local LuaClass = {}
